pluginGroup=com.github.nymann.commitrefactoring
pluginName=commit-refactoring
pluginRepositoryUrl=https://github.com/nymann/commit-refactoring
pluginVersion=0.2.1-beta
pluginSinceBuild=253
platformVersion=2025.3.2
platformBundledPlugins=Git4Idea
gradleVersion=8.13
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4g
